### ISSUE TITLE
Yosemite support

### ISSUE THREAD

**Issue by martinbohman** [Antrikshy/RecoverTabs#1]
Hi!
Does this have Yosemite support? I cannot get it to work but maybe it is colliding with another extension (that I cannot remove...)

**Comment by Antrikshy** [comment]
I haven't tested myself, actually. In Mavericks, Cmd+Shift+T is mapped to hide/show tab bar, which causes the extension to not function properly sometimes. A workaround is to change this mapping to Cmd+Option+T in System Preferences. In the future, I will try to implement a way to customize the keyboard shortcut for this extension.

**Comment by erlingur** [comment]
I can confirm it works in Yosemite!

**Comment by Antrikshy** [comment]
@erlingur Thanks for the confirmation!

**Comment by erlingur** [comment]
No problem!
